artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: 
    - 'https://drive.google.com/file/d/1nZEHX3_xK0gUYiDCJoJ3CecARvIrQDlF/view?usp=sharing'
    - 'https://drive.google.com/file/d/1xo0d7jACK7yxmMpGA-PnPLLRxv5aLuxI/view?usp=sharing'
  local_data_file: artifacts/data_ingestion
  csv_dir: 
    - artifacts/data_ingestion/validation
    - artifacts/data_ingestion/raw

data_validation:
  root_dir: artifacts/data_validation
  csv_dir: artifacts/data_ingestion/raw
  STATUS_FILE: artifacts/data_validation/status.txt